# Generated by Django 5.1.15 on 2026-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления предложения в избранное.', verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Избранное предложение',
                'verbose_name_plural': 'Избранные предложения',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wb', 'Wildberries'), ('ym', 'Yandex Market')], default='ozon', help_text='Выберите маркетплейс, на котором размещено предложение.', max_length=25, verbose_name='Marketplace')),
                ('title', models.CharField(max_length=200)),
                ('external_id', models.CharField(db_index=True, help_text='Уникальный идентификатор предложения на маркетплейсе.', max_length=100, unique=True, verbose_name='ID товара')),
                ('url', models.URLField(help_text='URL предложения на маркетплейсе.', max_length=1000, verbose_name='ссылка на предложение')),
                ('image_url', models.URLField(help_text='URL изображения товара на маркетплейсе.', max_length=1000, verbose_name='ссылка на изображение')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена предложения на маркетплейсе.', max_digits=10, verbose_name='Цена')),
                ('created_by', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания предложения в системе.', verbose_name='Дата создания')),
                ('updated_by', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления предложения в системе.', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Предложение товара',
                'verbose_name_plural': 'Предложения товаров',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Текст поискового запроса, введенного пользователем.', max_length=255, verbose_name='Поисковый запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время выполнения поискового запроса.', verbose_name='Дата поиска')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
