# Generated by Django 5.1.15 on 2026-06-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который добавил предложение в избранное.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='productoffer',
            unique_together={('marketplace', 'external_id')},
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='product',
            field=models.ForeignKey(help_text='Предложение товара, добавленное в избранное пользователем.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.productoffer', verbose_name='Предложение товара'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который выполнил поиск.', on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together={('user', 'product')},
        ),
    ]
